//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "comsci_pins.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom_map.h"
#include "driverlib/gpio.h"

//*****************************************************************************
void
PortFunctionInit(void)
{
    //
    // Enable Peripheral Clocks 
    //
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_SSI0);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_SSI2);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_USB0);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_UART0);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_I2C1);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_I2C2);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_UART2);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOB);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOD);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOG);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOJ);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOK);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOL);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOM);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPION);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOP);

    //
    // Enable pin PA6 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTA_BASE, GPIO_PIN_6);

    //
    // Enable pin PA7 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTA_BASE, GPIO_PIN_7);

    //
    // Enable pin PG4 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTG_BASE, GPIO_PIN_4);

    //
    // Enable pin PJ1 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTJ_BASE, GPIO_PIN_1);

    //
    // Enable pin PJ0 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTJ_BASE, GPIO_PIN_0);

    //
    // Enable pin PK3 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTK_BASE, GPIO_PIN_3);

    //
    // Enable pin PK4 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTK_BASE, GPIO_PIN_4);

    //
    // Enable pin PK5 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTK_BASE, GPIO_PIN_5);

    //
    // Enable pin PK1 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTK_BASE, GPIO_PIN_1);

    //
    // Enable pin PK2 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTK_BASE, GPIO_PIN_2);

    //
    // Enable pin PK6 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTK_BASE, GPIO_PIN_6);

    //
    // Enable pin PK0 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTK_BASE, GPIO_PIN_0);

    //
    // Enable pin PK7 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTK_BASE, GPIO_PIN_7);

    //
    // Enable pin PM7 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTM_BASE, GPIO_PIN_7);

    //
    // Enable pin PM6 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTM_BASE, GPIO_PIN_6);

    //
    // Enable pin PM4 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTM_BASE, GPIO_PIN_4);

    //
    // Enable pin PM5 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTM_BASE, GPIO_PIN_5);

    //
    // Enable pin PM2 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTM_BASE, GPIO_PIN_2);

    //
    // Enable pin PM3 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTM_BASE, GPIO_PIN_3);

    //
    // Enable pin PM0 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTM_BASE, GPIO_PIN_0);

    //
    // Enable pin PM1 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTM_BASE, GPIO_PIN_1);

    //
    // Enable pin PN2 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTN_BASE, GPIO_PIN_2);

    //
    // Enable pin PN3 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTN_BASE, GPIO_PIN_3);

    //
    // Enable pin PG1 for I2C1 I2C1SDA
    //
    MAP_GPIOPinConfigure(GPIO_PG1_I2C1SDA);
    MAP_GPIOPinTypeI2C(GPIO_PORTG_BASE, GPIO_PIN_1);

    //
    // Enable pin PG0 for I2C1 I2C1SCL
    //
    MAP_GPIOPinConfigure(GPIO_PG0_I2C1SCL);
    MAP_GPIOPinTypeI2CSCL(GPIO_PORTG_BASE, GPIO_PIN_0);

    //
    // Enable pin PN5 for I2C2 I2C2SCL
    //
    MAP_GPIOPinConfigure(GPIO_PN5_I2C2SCL);
    MAP_GPIOPinTypeI2CSCL(GPIO_PORTN_BASE, GPIO_PIN_5);

    //
    // Enable pin PN4 for I2C2 I2C2SDA
    //
    MAP_GPIOPinConfigure(GPIO_PN4_I2C2SDA);
    MAP_GPIOPinTypeI2C(GPIO_PORTN_BASE, GPIO_PIN_4);

    //
    // Enable pin PA4 for SSI0 SSI0XDAT0
    //
    MAP_GPIOPinConfigure(GPIO_PA4_SSI0XDAT0);
    MAP_GPIOPinTypeSSI(GPIO_PORTA_BASE, GPIO_PIN_4);

    //
    // Enable pin PA2 for SSI0 SSI0CLK
    //
    MAP_GPIOPinConfigure(GPIO_PA2_SSI0CLK);
    MAP_GPIOPinTypeSSI(GPIO_PORTA_BASE, GPIO_PIN_2);

    //
    // Enable pin PA3 for SSI0 SSI0FSS
    //
    MAP_GPIOPinConfigure(GPIO_PA3_SSI0FSS);
    MAP_GPIOPinTypeSSI(GPIO_PORTA_BASE, GPIO_PIN_3);

    //
    // Enable pin PA5 for SSI0 SSI0XDAT1
    //
    MAP_GPIOPinConfigure(GPIO_PA5_SSI0XDAT1);
    MAP_GPIOPinTypeSSI(GPIO_PORTA_BASE, GPIO_PIN_5);

    //
    // Enable pin PD2 for SSI2 SSI2FSS
    //
    MAP_GPIOPinConfigure(GPIO_PD2_SSI2FSS);
    MAP_GPIOPinTypeSSI(GPIO_PORTD_BASE, GPIO_PIN_2);

    //
    // Enable pin PD1 for SSI2 SSI2XDAT0
    //
    MAP_GPIOPinConfigure(GPIO_PD1_SSI2XDAT0);
    MAP_GPIOPinTypeSSI(GPIO_PORTD_BASE, GPIO_PIN_1);

    //
    // Enable pin PD0 for SSI2 SSI2XDAT1
    //
    MAP_GPIOPinConfigure(GPIO_PD0_SSI2XDAT1);
    MAP_GPIOPinTypeSSI(GPIO_PORTD_BASE, GPIO_PIN_0);

    //
    // Enable pin PG2 for SSI2 SSI2XDAT3
    //
    MAP_GPIOPinConfigure(GPIO_PG2_SSI2XDAT3);
    MAP_GPIOPinTypeSSI(GPIO_PORTG_BASE, GPIO_PIN_2);

    //
    // Enable pin PD3 for SSI2 SSI2CLK
    //
    MAP_GPIOPinConfigure(GPIO_PD3_SSI2CLK);
    MAP_GPIOPinTypeSSI(GPIO_PORTD_BASE, GPIO_PIN_3);

    //
    // Enable pin PG3 for SSI2 SSI2XDAT2
    //
    MAP_GPIOPinConfigure(GPIO_PG3_SSI2XDAT2);
    MAP_GPIOPinTypeSSI(GPIO_PORTG_BASE, GPIO_PIN_3);

    //
    // Enable pin PA0 for UART0 U0RX
    //
    MAP_GPIOPinConfigure(GPIO_PA0_U0RX);
    MAP_GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_0);

    //
    // Enable pin PA1 for UART0 U0TX
    //
    MAP_GPIOPinConfigure(GPIO_PA1_U0TX);
    MAP_GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_1);

    //
    // Enable pin PD4 for UART2 U2RX
    //
    MAP_GPIOPinConfigure(GPIO_PD4_U2RX);
    MAP_GPIOPinTypeUART(GPIO_PORTD_BASE, GPIO_PIN_4);

    //
    // Enable pin PD5 for UART2 U2TX
    //
    MAP_GPIOPinConfigure(GPIO_PD5_U2TX);
    MAP_GPIOPinTypeUART(GPIO_PORTD_BASE, GPIO_PIN_5);

    //
    // Enable pin PL2 for USB0 USB0D2
    //
    MAP_GPIOPinConfigure(GPIO_PL2_USB0D2);
    MAP_GPIOPinTypeUSBDigital(GPIO_PORTL_BASE, GPIO_PIN_2);

    //
    // Enable pin PP2 for USB0 USB0NXT
    //
    MAP_GPIOPinConfigure(GPIO_PP2_USB0NXT);
    MAP_GPIOPinTypeUSBDigital(GPIO_PORTP_BASE, GPIO_PIN_2);

    //
    // Enable pin PP4 for USB0 USB0D7
    //
    MAP_GPIOPinConfigure(GPIO_PP4_USB0D7);
    MAP_GPIOPinTypeUSBDigital(GPIO_PORTP_BASE, GPIO_PIN_4);

    //
    // Enable pin PD6 for USB0 USB0EPEN
    //
    MAP_GPIOPinConfigure(GPIO_PD6_USB0EPEN);
    MAP_GPIOPinTypeUSBDigital(GPIO_PORTD_BASE, GPIO_PIN_6);

    //
    // Enable pin PL4 for USB0 USB0D4
    //
    MAP_GPIOPinConfigure(GPIO_PL4_USB0D4);
    MAP_GPIOPinTypeUSBDigital(GPIO_PORTL_BASE, GPIO_PIN_4);

    //
    // Enable pin PB3 for USB0 USB0CLK
    //
    MAP_GPIOPinConfigure(GPIO_PB3_USB0CLK);
    MAP_GPIOPinTypeUSBDigital(GPIO_PORTB_BASE, GPIO_PIN_3);

    //
    // Enable pin PP5 for USB0 USB0D6
    //
    MAP_GPIOPinConfigure(GPIO_PP5_USB0D6);
    MAP_GPIOPinTypeUSBDigital(GPIO_PORTP_BASE, GPIO_PIN_5);

    //
    // Enable pin PP3 for USB0 USB0DIR
    //
    MAP_GPIOPinConfigure(GPIO_PP3_USB0DIR);
    MAP_GPIOPinTypeUSBDigital(GPIO_PORTP_BASE, GPIO_PIN_3);

    //
    // Enable pin PL1 for USB0 USB0D1
    //
    MAP_GPIOPinConfigure(GPIO_PL1_USB0D1);
    MAP_GPIOPinTypeUSBDigital(GPIO_PORTL_BASE, GPIO_PIN_1);

    //
    // Enable pin PL5 for USB0 USB0D5
    //
    MAP_GPIOPinConfigure(GPIO_PL5_USB0D5);
    MAP_GPIOPinTypeUSBDigital(GPIO_PORTL_BASE, GPIO_PIN_5);

    //
    // Enable pin PB2 for USB0 USB0STP
    //
    MAP_GPIOPinConfigure(GPIO_PB2_USB0STP);
    MAP_GPIOPinTypeUSBDigital(GPIO_PORTB_BASE, GPIO_PIN_2);

    //
    // Enable pin PL6 for USB0 USB0DP
    //
    MAP_GPIOPinTypeUSBAnalog(GPIO_PORTL_BASE, GPIO_PIN_6);

    //
    // Enable pin PD7 for USB0 USB0PFLT
    // First open the lock and select the bits we want to modify in the GPIO commit register.
    //
    HWREG(GPIO_PORTD_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
    HWREG(GPIO_PORTD_BASE + GPIO_O_CR) = 0x80;

    //
    // Now modify the configuration of the pins that we unlocked.
    //
    MAP_GPIOPinConfigure(GPIO_PD7_USB0PFLT);
    MAP_GPIOPinTypeUSBDigital(GPIO_PORTD_BASE, GPIO_PIN_7);

    //
    // Enable pin PL3 for USB0 USB0D3
    //
    MAP_GPIOPinConfigure(GPIO_PL3_USB0D3);
    MAP_GPIOPinTypeUSBDigital(GPIO_PORTL_BASE, GPIO_PIN_3);

    //
    // Enable pin PL0 for USB0 USB0D0
    //
    MAP_GPIOPinConfigure(GPIO_PL0_USB0D0);
    MAP_GPIOPinTypeUSBDigital(GPIO_PORTL_BASE, GPIO_PIN_0);

    //
    // Enable pin PB1 for USB0 USB0VBUS
    //
    MAP_GPIOPinTypeUSBAnalog(GPIO_PORTB_BASE, GPIO_PIN_1);

    //
    // Enable pin PL7 for USB0 USB0DM
    //
    MAP_GPIOPinTypeUSBAnalog(GPIO_PORTL_BASE, GPIO_PIN_7);

    //
    // Enable pin PB0 for USB0 USB0ID
    //
    MAP_GPIOPinTypeUSBAnalog(GPIO_PORTB_BASE, GPIO_PIN_0);
}
